language: 'node_js'
node_js: '10'

before_script:
  - yarn build-storybook

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: regulyarniy/react-essential-tools
  target_branch: gh-pages
  on:
    branch: master
